import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const musicDataContent = `// Spotify Rich Music Streaming Data with Authentic Studio Audio

export const categories = [
  { id: 'pop', name: 'Pop', color: 'from-pink-600 to-rose-700', image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&auto=format&fit=crop&q=80' },
  { id: 'hip-hop', name: 'Hip-Hop', color: 'from-orange-600 to-amber-700', image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&auto=format&fit=crop&q=80' },
  { id: 'rock', name: 'Rock Classics', color: 'from-red-600 to-rose-900', image: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=400&auto=format&fit=crop&q=80' },
  { id: 'electronic', name: 'Dance & EDM', color: 'from-cyan-600 to-blue-700', image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&auto=format&fit=crop&q=80' },
  { id: 'chill', name: 'Chill & Lofi', color: 'from-indigo-600 to-purple-800', image: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=80' },
  { id: 'indie', name: 'Indie & Alt', color: 'from-emerald-600 to-teal-800', image: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=400&auto=format&fit=crop&q=80' },
  { id: 'rnb', name: 'R&B & Soul', color: 'from-purple-700 to-pink-800', image: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=400&auto=format&fit=crop&q=80' },
  { id: 'workout', name: 'Workout Power', color: 'from-lime-600 to-emerald-800', image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&auto=format&fit=crop&q=80' },
  { id: 'focus', name: 'Deep Focus', color: 'from-teal-600 to-cyan-800', image: 'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=400&auto=format&fit=crop&q=80' },
  { id: 'latin', name: 'Latin Vibes', color: 'from-yellow-600 to-red-600', image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&auto=format&fit=crop&q=80' },
  { id: 'jazz', name: 'Jazz & Blues', color: 'from-amber-700 to-yellow-900', image: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=400&auto=format&fit=crop&q=80' },
  { id: 'podcasts', name: 'Podcasts', color: 'from-emerald-700 to-green-900', image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400&auto=format&fit=crop&q=80' },
  { id: 'bollywood', name: 'Bollywood & Desi', color: 'from-amber-600 to-rose-700', image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&auto=format&fit=crop&q=80' },
  { id: 'k-pop', name: 'K-Pop', color: 'from-purple-600 to-pink-600', image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&auto=format&fit=crop&q=80' },
];

export const tracks = [
  // --- THE WEEKND ---
  {
    id: 'track-1',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    artistId: 'artist-the-weeknd',
    album: 'After Hours',
    duration: '3:20',
    durationSec: 200,
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-1.m4a',
    plays: '4,102,400,900',
    lyrics: "I've been on my own for long enough\\nMaybe you can show me how to love, maybe\\nI'm going through withdrawals\\nYou don't even have to do too much\\nSin city's cold and empty\\nNo one's around to judge me\\nI can't see clearly when you're gone\\nI said, ooh, I'm blinded by the lights\\nNo, I can't sleep until I feel your touch",
    color: '#8b0000',
  },
  {
    id: 'track-5',
    title: 'Starboy (feat. Daft Punk)',
    artist: 'The Weeknd',
    artistId: 'artist-the-weeknd',
    album: 'Starboy',
    duration: '3:50',
    durationSec: 230,
    cover: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-5.m4a',
    plays: '3,240,119,400',
    lyrics: "I'm tryna put you in the worst mood, ah\\nP1 cleaner than your church shoes, ah\\nMilli point two just to hurt you, ah\\nAll red Lamb' just to tease you, ah\\nNone of these toys on lease too, ah\\nMade your whole year in a week too, yah\\nMain girl out your league too, ah\\nLook what you've done, I'm a motherfuckin' starboy",
    color: '#0284c7',
  },
  {
    id: 'track-11',
    title: 'Save Your Tears',
    artist: 'The Weeknd',
    artistId: 'artist-the-weeknd',
    album: 'After Hours',
    duration: '3:35',
    durationSec: 215,
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-11.m4a',
    plays: '2,190,500,120',
    lyrics: "I saw you dancing in a crowded room\\nYou look so happy when I'm not with you\\nBut then you saw me, caught you by surprise\\nA single teardrop falling from your eye\\nI don't know why I run away\\nI'll make you cry when I run away\\nTake me back 'cause I wanna stay\\nSave your tears for another day",
    color: '#6366f1',
  },

  // --- DUA LIPA ---
  {
    id: 'track-2',
    title: 'Levitating',
    artist: 'Dua Lipa',
    artistId: 'artist-dua-lipa',
    album: 'Future Nostalgia',
    duration: '3:23',
    durationSec: 203,
    cover: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-2.m4a',
    plays: '2,580,915,800',
    lyrics: "If you wanna run away with me, I know a galaxy\\nAnd I can take you for a ride\\nI had a premonition that we fell into a rhythm\\nWhere the music don't stop for life\\nGlitter in the sky, glitter in my eyes\\nShining just the way I like\\nIf you're feeling like you need a little bit of company\\nYou met me at the perfect time\\nYou want me, I want you, baby\\nMy sugarboo, I'm levitating",
    color: '#3b82f6',
  },
  {
    id: 'track-10',
    title: "Don't Start Now",
    artist: 'Dua Lipa',
    artistId: 'artist-dua-lipa',
    album: 'Future Nostalgia',
    duration: '3:03',
    durationSec: 183,
    cover: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-10.m4a',
    plays: '2,410,480,000',
    lyrics: "Did a full 180, crazy\\nThinking 'bout the way I was\\nDid the heartbreak change me? Maybe\\nBut look at where I ended up\\nI'm all good already\\nSo moved on, it's scary\\nI'm not where you left me at all, so\\nIf you don't wanna see me dancing with somebody\\nDon't show up, don't come out\\nDon't start caring about me now",
    color: '#10b981',
  },

  // --- BTS ---
  {
    id: 'track-bts-1',
    title: 'Dynamite',
    artist: 'BTS',
    artistId: 'artist-bts',
    album: 'BE',
    duration: '3:19',
    durationSec: 199,
    cover: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-bts-1.m4a',
    plays: '1,980,204,500',
    lyrics: "'Cause I, I, I'm in the stars tonight\\nSo watch me bring the fire and set the night alight\\nShoes on, get up in the morn'\\nCup of milk, let's rock and roll\\nKing Kong, kick the drum\\nRolling on like a Rolling Stone\\nSing song when I'm walking home\\nJump up to the top, LeBron\\nDing-dong, call me on my phone\\nIce tea and a game of ping pong\\nDisco overload, I'm into that, I'm good to go\\nI'm diamond, you know I glow up\\nHey, so let's go!",
    color: '#f59e0b',
  },
  {
    id: 'track-bts-2',
    title: 'Butter',
    artist: 'BTS',
    artistId: 'artist-bts',
    album: 'Butter',
    duration: '2:44',
    durationSec: 164,
    cover: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-bts-2.m4a',
    plays: '1,410,105,800',
    lyrics: "Smooth like butter, like a criminal undercover\\nGon' pop like trouble breaking into your heart like that\\nCool shade, stunner, yeah, I owe it all to my mother\\nHot like summer, yeah, I'm making you sweat like that\\nBreak it down\\nOh, when I look in the mirror\\nI'll melt your heart into two\\nI got that superstar glow, so\\nSide step, right-left, to my beat\\nHigh like the moon, rock with me, baby\\nKnow that I got that heat\\nGet it, let it roll!",
    color: '#eab308',
  },
  {
    id: 'track-bts-3',
    title: 'Boy With Luv (feat. Halsey)',
    artist: 'BTS',
    artistId: 'artist-bts',
    album: 'Map of the Soul: 7',
    duration: '3:49',
    durationSec: 229,
    cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-bts-3.m4a',
    plays: '1,280,830,400',
    lyrics: "모든 게 궁금해 how's your day\\nOh, tell me\\n뭐가 널 행복하게 하는지\\nOh, text me\\nYour every picture\\n내 머리맡에 두고 싶어, oh, bae\\nCome be my teacher\\n네 모든 걸 다 가르쳐줘\\nYour 1, your 2\\nListen, my my baby, 나는\\n저 하늘을 높이 날고 있어\\nYeah, you makin' me a boy with luv",
    color: '#ec4899',
  },
  {
    id: 'track-bts-4',
    title: 'Blood Sweat & Tears',
    artist: 'BTS',
    artistId: 'artist-bts',
    album: 'Wings',
    duration: '3:37',
    durationSec: 217,
    cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-bts-4.m4a',
    plays: '740,450,120',
    lyrics: "내 피 땀 눈물, 내 마지막 춤을\\n다 가져가 가\\n내 피 땀 눈물, 내 차가운 숨을\\n다 가져가 가\\n내 피 땀 눈물\\n내 몸 마음 영혼도\\n너의 것인 걸 잘 알고 있어\\nPeaches and cream, sweeter than sweet\\nChocolate cheeks and chocolate wings\\nKiss me, 아파도 돼, 빨리 날 옭아매줘",
    color: '#8b5cf6',
  },
  {
    id: 'track-bts-5',
    title: 'Life Goes On',
    artist: 'BTS',
    artistId: 'artist-bts',
    album: 'BE',
    duration: '3:27',
    durationSec: 207,
    cover: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-bts-5.m4a',
    plays: '810,910,340',
    lyrics: "어느 날 세상이 멈췄어\\n아무런 예고도 하나 없이\\n봄은 기다림을 몰라서\\n눈치 없이 와버렸어\\n발자국이 지워진 거리\\n여기 넘어져 있는 나\\nLike an echo in the forest\\n하루가 돌아오겠지\\n아무 일도 없단 듯이\\nYeah, life goes on",
    color: '#06b6d4',
  },
  {
    id: 'track-bts-6',
    title: 'Fake Love',
    artist: 'BTS',
    artistId: 'artist-bts',
    album: 'Love Yourself: Tear',
    duration: '4:02',
    durationSec: 242,
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-bts-6.m4a',
    plays: '890,490,200',
    lyrics: "널 위해서라면 난 슬퍼도 기쁜 척 할 수가 있었어\\n널 위해서라면 난 아파도 강한 척 할 수가 있었어\\n사랑이 사랑만으로 완벽하길\\n내 모든 약점들은 다 숨겨지길\\n이뤄지지 않는 꿈속에서\\n피울 수 없는 꽃을 키웠어\\nI'm so sick of this fake love, fake love, fake love\\nI'm so sorry but it's fake love, fake love, fake love",
    color: '#3b82f6',
  },
  {
    id: 'track-bts-7',
    title: 'Spring Day',
    artist: 'BTS',
    artistId: 'artist-bts',
    album: 'You Never Walk Alone',
    duration: '4:34',
    durationSec: 274,
    cover: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-bts-7.m4a',
    plays: '690,119,400',
    lyrics: "보고 싶다, 이렇게 말하니까 더 보고 싶다\\n너희 사진을 보고 있어도 보고 싶다\\n너무 야속한 시간, 나는 우리가 밉다\\n이젠 얼굴 한 번 보는 것 조차 힘겨워진 우리가\\n여긴 온통 겨울 뿐이야, 8월에도 겨울이 와\\n마음은 시간을 달려가네, 홀로 남은 설국열차\\n니 손 잡고 지구 반대편까지 가 겨울을 끝내고파",
    color: '#06b6d4',
  },
  {
    id: 'track-bts-8',
    title: 'DNA',
    artist: 'BTS',
    artistId: 'artist-bts',
    album: 'Love Yourself: Her',
    duration: '3:43',
    durationSec: 223,
    cover: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-bts-8.m4a',
    plays: '1,020,830,100',
    lyrics: "첫눈에 널 알아보게 됐어, 서롤 불러왔던 것처럼\\n내 혈관 속 DNA가 말해줘\\n내가 찾아 헤매던 너라는 걸\\n우리 만남은 수학의 공식, 종교의 율법 우주의 섭리\\n내게 주어진 운명의 증거, 너는 내 꿈의 출처\\nTake it, take it, 너에게 내민 내 손은 정해진 숙명\\n걱정하지 마 love, 이 모든 건 우연이 아니니까",
    color: '#eab308',
  },
  {
    id: 'track-bts-9',
    title: 'Mic Drop (Steve Aoki Remix)',
    artist: 'BTS',
    artistId: 'artist-bts',
    album: 'Love Yourself: Her',
    duration: '3:58',
    durationSec: 238,
    cover: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-bts-9.m4a',
    plays: '810,290,500',
    lyrics: "Yeah, 누가 내 수저 더럽대\\nI don't care, 마이크 잡음 금수저 여럿 패\\nWorld business 핵심, 섭외 1순위 매진\\n매각 없는 클라스 가치를 누려\\nMic mic bungee, bright lights 전진\\n망할 것 같았겠지만 I'm fine, sorry\\n미안해 Billboard, 미안해 worldwide\\n아들이 넘 잘나가서 미안해 엄마",
    color: '#ef4444',
  },
  {
    id: 'track-bts-10',
    title: 'Permission to Dance',
    artist: 'BTS',
    artistId: 'artist-bts',
    album: 'Butter',
    duration: '3:07',
    durationSec: 187,
    cover: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-bts-10.m4a',
    plays: '910,440,200',
    lyrics: "It's the thought of being young\\nWhen your heart's just like a drum\\nBeating at the pace of our emotions\\nThere's no need to talk the talk, just walk the walk tonight\\n'Cause we don't need permission to dance\\nThere's always something that's standing in the way\\nBut if you don't let it faze ya, you'll know just how to break\\nWe don't need permission to dance!",
    color: '#a855f7',
  },

  // --- TAYLOR SWIFT ---
  {
    id: 'track-taylor-1',
    title: 'Cruel Summer',
    artist: 'Taylor Swift',
    artistId: 'artist-taylor-swift',
    album: 'Lover',
    duration: '2:58',
    durationSec: 178,
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-taylor-1.m4a',
    plays: '2,640,105,400',
    lyrics: "Fever dream high in the quiet of the night\\nYou know that I caught it\\nBad, bad boy, shiny toy with a price\\nYou know that I bought it\\nKilling me slow, out the window\\nI'm always waiting for you to be waiting below\\nDevils roll the dice, angels roll their eyes\\nWhat doesn't kill me makes me want you more\\nAnd it's new, the shape of your body\\nIt's blue, the feeling I've got\\nAnd it's ooh, whoa, oh\\nIt's a cruel summer!",
    color: '#f43f5e',
  },
  {
    id: 'track-taylor-2',
    title: 'Anti-Hero',
    artist: 'Taylor Swift',
    artistId: 'artist-taylor-swift',
    album: 'Midnights',
    duration: '3:20',
    durationSec: 200,
    cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-taylor-2.m4a',
    plays: '1,890,400,100',
    lyrics: "I have this thing where I get older, but just never wiser\\nMidnights become my afternoons\\nWhen my depression works the graveyard shift\\nAll of the people I've ghosted stand there in the room\\nI should not be left to my own devices\\nThey come with prices and vices, I end up in crisis\\nIt's me, hi, I'm the problem, it's me\\nAt tea time, everybody agrees\\nI'll stare directly at the sun, but never in the mirror\\nIt must be exhausting always rooting for the anti-hero",
    color: '#3b82f6',
  },

  // --- SABRINA CARPENTER ---
  {
    id: 'track-sabrina-1',
    title: 'Espresso',
    artist: 'Sabrina Carpenter',
    artistId: 'artist-sabrina-carpenter',
    album: 'Short n\\' Sweet',
    duration: '2:55',
    durationSec: 175,
    cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-sabrina-1.m4a',
    plays: '1,820,890,300',
    lyrics: "Now he's thinkin' 'bout me every night, oh\\nIs it that sweet? I guess so\\nSay you can't sleep, baby, I know\\nThat's that me, espresso\\nMove it up, down, left, right, oh\\nSwitch it up like Nintendo\\nSay you can't sleep, baby, I know\\nThat's that me, espresso\\nHoly shit, I'm cute as hell\\nI know you want this, I can tell",
    color: '#d97706',
  },
  {
    id: 'track-sabrina-2',
    title: 'Please Please Please',
    artist: 'Sabrina Carpenter',
    artistId: 'artist-sabrina-carpenter',
    album: 'Short n\\' Sweet',
    duration: '3:06',
    durationSec: 186,
    cover: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-sabrina-2.m4a',
    plays: '1,290,400,200',
    lyrics: "Please, please, please\\nDon't prove 'em right\\nAnd please, please, please\\nDon't bring me to tears when I just did my makeup so nice\\nHeartbreak is one thing, my ego's another\\nI beg you, don't embarrass me, motherfucker, ah\\nPlease, please, please",
    color: '#ec4899',
  },

  // --- BILLIE EILISH ---
  {
    id: 'track-4',
    title: 'bad guy',
    artist: 'Billie Eilish',
    artistId: 'artist-billie-eilish',
    album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    duration: '3:14',
    durationSec: 194,
    cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-4.m4a',
    plays: '2,780,443,009',
    lyrics: "White shirt now red, my bloody nose\\nSleepin', you're on your tippy toes\\nCreepin' around like no one knows\\nThink you're so criminal\\nBruises on both my knees for you\\nDon't say thank you or please\\nI do what I want when I'm wanting to\\nMy soul? So cynical\\nSo you're a tough guy, like it really rough guy\\nJust can't get enough guy, chest always so puffed guy\\nI'm that bad type, make-your-mama-sad type\\nMake-your-girlfriend-mad type, might-seduce-your-dad type\\nI'm the bad guy, duh",
    color: '#eab308',
  },
  {
    id: 'track-billie-2',
    title: 'BIRDS OF A FEATHER',
    artist: 'Billie Eilish',
    artistId: 'artist-billie-eilish',
    album: 'HIT ME HARD AND SOFT',
    duration: '3:30',
    durationSec: 210,
    cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-billie-2.m4a',
    plays: '2,140,300,450',
    lyrics: "I want you to stay\\n'Til I'm in the grave\\n'Til I'm rot and old\\nDead and buried, 'til I'm in the casket you carry\\nIf you go, I'm goin' too, uh\\n'Cause it was always you, alright\\nAnd if I'm turnin' blue, please don't save me\\nNothin' left to lose without my baby\\nBirds of a feather, we should stick together, I know\\nI said I'd never think I wasn't better alone",
    color: '#0284c7',
  },
  {
    id: 'track-15',
    title: 'ocean eyes',
    artist: 'Billie Eilish',
    artistId: 'artist-billie-eilish',
    album: 'dont smile at me',
    duration: '3:20',
    durationSec: 200,
    cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-15.m4a',
    plays: '1,890,240,000',
    lyrics: "I've been watchin' you for some time\\nCan't stop starin' at those ocean eyes\\nBurning cities and napalm skies\\nFifteen flares inside those ocean eyes\\nYour ocean eyes\\nNo fair\\nYou really know how to make me cry\\nWhen you gimme those ocean eyes",
    color: '#0ea5e9',
  },

  // --- KENDRICK LAMAR ---
  {
    id: 'track-8',
    title: 'HUMBLE.',
    artist: 'Kendrick Lamar',
    artistId: 'artist-kendrick-lamar',
    album: 'DAMN.',
    duration: '2:57',
    durationSec: 177,
    cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-8.m4a',
    plays: '2,240,480,900',
    lyrics: "Nobody pray for me\\nIt's been that day for me\\nWOO, beat that boy with a bat\\nAy, I remember syrup sandwiches and crime allowances\\nFinesse with some counterfeits, but now I'm countin' this\\nParmesan where my accountant lives\\nIn fact, I'm downin' this\\nBitch, be humble (hol' up, bitch)\\nSit down (hol' up, bitch, hol' up, bitch)",
    color: '#dc2626',
  },
  {
    id: 'track-14',
    title: 'DNA.',
    artist: 'Kendrick Lamar',
    artistId: 'artist-kendrick-lamar',
    album: 'DAMN.',
    duration: '3:05',
    durationSec: 185,
    cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-14.m4a',
    plays: '1,560,890,200',
    lyrics: "I got, I got, I got, I got\\nLoyalty, got royalty inside my DNA\\nCocaine quarter piece, got war and peace inside my DNA\\nI got power, poison, pain and joy inside my DNA\\nI got hustle though, ambition inside my DNA\\nI was born like this, since one like this, immaculate conception",
    color: '#ef4444',
  },
  {
    id: 'track-kendrick-2',
    title: 'Not Like Us',
    artist: 'Kendrick Lamar',
    artistId: 'artist-kendrick-lamar',
    album: 'GNX',
    duration: '4:34',
    durationSec: 274,
    cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-kendrick-2.m4a',
    plays: '1,490,450,900',
    lyrics: "Psst, I see dead people\\n(Mustard on the beat, ho)\\nSay, Drake, I hear you like 'em young\\nYou better not ever go to cell block one\\nWOP, WOP, WOP, WOP, WOP, Dot, fuck 'em up\\nWOP, WOP, WOP, WOP, WOP, I'ma do my stuff\\nWhy you trollin' like a bitch? Ain't you tired?\\nTryna strike a chord and it's probably A-minor",
    color: '#ef4444',
  },

  // --- DRAKE ---
  {
    id: 'track-drake-1',
    title: "God's Plan",
    artist: 'Drake',
    artistId: 'artist-drake',
    album: 'Scorpion',
    duration: '3:18',
    durationSec: 198,
    cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-drake-1.m4a',
    plays: '2,980,105,400',
    lyrics: "Yeah, they wish and wish and wish and wish\\nThey wishin' on me, yeah\\nI been movin' calm, don't start no trouble with me\\nTryna keep it peaceful is a struggle for me\\nDon't pull up at 6 AM to cuddle with me\\nYou know how I like it when you lovin' on me\\nI don't wanna die for them to miss me\\nYes, I see the things that they wishin' on me\\nHope I got some brothers that outlive me\\nThey gon' tell the story, shit was different with me\\nGod's plan, God's plan",
    color: '#f59e0b',
  },
  {
    id: 'track-drake-2',
    title: 'One Dance (feat. Wizkid & Kyla)',
    artist: 'Drake',
    artistId: 'artist-drake',
    album: 'Views',
    duration: '2:53',
    durationSec: 173,
    cover: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-drake-2.m4a',
    plays: '3,120,440,000',
    lyrics: "Baby, I like your style\\nGrips on your waist, front way, back way\\nYou know that I don't play\\nStreet took my heart, now I'm rollin' on\\n'Cause I need you here\\nThat's why I need a one dance\\nGot a Hennessy in my hand\\nOne more time 'fore I go\\nHigher powers takin' a hold on me\\nI need a one dance",
    color: '#06b6d4',
  },
  {
    id: 'track-drake-3',
    title: 'Hotline Bling',
    artist: 'Drake',
    artistId: 'artist-drake',
    album: 'Views',
    duration: '4:27',
    durationSec: 267,
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-drake-3.m4a',
    plays: '1,890,200,300',
    lyrics: "You used to call me on my cell phone\\nLate night when you need my love\\nCall me on my cell phone\\nLate night when you need my love\\nAnd I know when that hotline bling\\nThat can only mean one thing\\nI know when that hotline bling\\nThat can only mean one thing",
    color: '#ec4899',
  },

  // --- BRUNO MARS ---
  {
    id: 'track-bruno-1',
    title: 'Die With A Smile',
    artist: 'Lady Gaga & Bruno Mars',
    artistId: 'artist-bruno-mars',
    album: 'Die With A Smile',
    duration: '4:11',
    durationSec: 251,
    cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-bruno-1.m4a',
    plays: '1,720,220,900',
    lyrics: "I, I just woke up from a dream\\nWhere you and I had to say goodbye\\nAnd I don't know what it all means\\nBut since I survived, I realized\\nWherever you go, that's where I'll follow\\nNobody's promised tomorrow\\nSo I'ma love you every night like it's the last night\\nIf the world was ending, I'd wanna be next to you\\nIf the party was over and our time on Earth was through\\nI'd wanna hold you just for a while\\nAnd die with a smile",
    color: '#dc2626',
  },
  {
    id: 'track-bruno-2',
    title: '24K Magic',
    artist: 'Bruno Mars',
    artistId: 'artist-bruno-mars',
    album: '24K Magic',
    duration: '3:46',
    durationSec: 226,
    cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-bruno-2.m4a',
    plays: '2,040,119,000',
    lyrics: "Tonight, I just want to take you higher\\nThrow your hands up in the sky\\nLet's set this party off right\\nPlayers, put yo' pinky rings up to the moon\\nGirls, what y'all tryin' to do?\\n24 karat magic in the air\\nHead to toe so player\\nUh, look out!",
    color: '#f59e0b',
  },
  {
    id: 'track-bruno-3',
    title: "That's What I Like",
    artist: 'Bruno Mars',
    artistId: 'artist-bruno-mars',
    album: '24K Magic',
    duration: '3:26',
    durationSec: 206,
    cover: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-bruno-3.m4a',
    plays: '2,320,400,000',
    lyrics: "Hey, hey, hey\\nI got a condo in Manhattan\\nBaby girl, what's happenin'?\\nYou and your ass invited\\nSo gon' and get to clappin'\\nSo pop it for a player, pop-pop it for me\\nTurn around and drop it for a player, drop-drop it for me\\nI'll rent a beach house in Miami\\nWake up with no jammies\\nLobster tail for dinner\\nJulio, serve that scampi",
    color: '#eab308',
  },

  // --- POST MALONE ---
  {
    id: 'track-post-1',
    title: 'Sunflower',
    artist: 'Post Malone & Swae Lee',
    artistId: 'artist-post-malone',
    album: 'Spider-Man: Into the Spider-Verse',
    duration: '2:38',
    durationSec: 158,
    cover: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-post-1.m4a',
    plays: '3,380,480,000',
    lyrics: "Ayy, ayy, ayy, ayy (ooh)\\nOoh, ooh, ooh, ooh (ayy, ayy)\\nNeedless to say, I keep in check\\nShe was a bad-bad, nevertheless (yeah)\\nCallin' it quits now, baby, I'm a wreck (wreck)\\nCrash at my place, baby, you're a wreck (wreck)\\nThinkin' in a bad way, losin' your grip\\nScreamin' at my face, baby, don't trip\\nThen you're left in the dust, unless I stuck by ya\\nYou're a sunflower, I think your love would be too much",
    color: '#eab308',
  },
  {
    id: 'track-post-2',
    title: 'Circles',
    artist: 'Post Malone',
    artistId: 'artist-post-malone',
    album: "Hollywood's Bleeding",
    duration: '3:35',
    durationSec: 215,
    cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-post-2.m4a',
    plays: '2,640,119,000',
    lyrics: "Seasons change and our love went cold\\nFeed the flame 'cause we can't let go\\nRun away, but we're running in circles\\nRun away, run away\\nI dare you to do something\\nI'm waiting on you again, so I don't take the blame\\nRun away, but we're running in circles\\nRun away, run away, run away",
    color: '#f97316',
  },
  {
    id: 'track-post-3',
    title: 'rockstar (feat. 21 Savage)',
    artist: 'Post Malone',
    artistId: 'artist-post-malone',
    album: 'beerbongs & bentleys',
    duration: '3:38',
    durationSec: 218,
    cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-post-3.m4a',
    plays: '2,920,800,000',
    lyrics: "Ayy, I've been fuckin' hoes and poppin' pillies\\nMan, I feel just like a rockstar (star, ayy, ayy)\\nAll my brothers got that gas\\nAnd they always be smokin' like a Rasta\\nFuckin' with me, call up on a shotty\\nHey, ayy, like a rockstar",
    color: '#ef4444',
  },

  // --- ARIANA GRANDE ---
  {
    id: 'track-ariana-1',
    title: "we can't be friends (wait for your love)",
    artist: 'Ariana Grande',
    artistId: 'artist-ariana-grande',
    album: 'eternal sunshine',
    duration: '3:48',
    durationSec: 228,
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-ariana-1.m4a',
    plays: '1,420,500,000',
    lyrics: "I didn't think you'd understand me\\nHow could you ever even try?\\nI don't wanna tiptoe, but I don't wanna hide\\nWe can't be friends\\nWait for your love\\nLove me until the sun comes down\\nWait for your love\\nI'll wait for your love",
    color: '#ec4899',
  },
  {
    id: 'track-ariana-2',
    title: '7 rings',
    artist: 'Ariana Grande',
    artistId: 'artist-ariana-grande',
    album: 'thank u, next',
    duration: '2:58',
    durationSec: 178,
    cover: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-ariana-2.m4a',
    plays: '2,310,400,000',
    lyrics: "Breakfast at Tiffany's and bottles of bubbles\\nGirls with tattoos who like getting in trouble\\nLashes and diamonds, ATM machines\\nBuy myself all of my favorite things\\nBeen through some bad shit, I should be a sad bitch\\nWho woulda thought it'd turn me to a savage?\\nRather be tied up with calls and not strings\\nWrite my own checks like I write what I sing, yeah\\nI want it, I got it, I want it, I got it",
    color: '#d946ef',
  },
  {
    id: 'track-ariana-3',
    title: 'positions',
    artist: 'Ariana Grande',
    artistId: 'artist-ariana-grande',
    album: 'Positions',
    duration: '2:52',
    durationSec: 172,
    cover: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-ariana-3.m4a',
    plays: '1,680,200,000',
    lyrics: "Heaven sent you to me\\nI'm just hopin' I don't repeat history\\nBoy, I'm tryna meet your mama on a Sunday\\nThen make a lotta love on a Monday (ah, yeah)\\nNever need no (no), no one else, babe\\n'Cause I'll be\\nSwitchin' the positions for you\\nCookin' in the kitchen and I'm in the bedroom",
    color: '#8b5cf6',
  },

  // --- ED SHEERAN ---
  {
    id: 'track-ed-1',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    artistId: 'artist-ed-sheeran',
    album: '÷ (Divide)',
    duration: '3:53',
    durationSec: 233,
    cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-ed-1.m4a',
    plays: '3,890,105,000',
    lyrics: "The club isn't the best place to find a lover\\nSo the bar is where I go\\nMe and my friends at the table doin' shots\\nDrinkin' fast and then we talk slow\\nGirl, you know I want your love\\nYour love was handmade for somebody like me\\nCome on now, follow my lead\\nI'm in love with the shape of you\\nWe push and pull like a magnet do\\nAlthough my heart is falling too\\nI'm in love with your body",
    color: '#0284c7',
  },
  {
    id: 'track-ed-2',
    title: 'Perfect',
    artist: 'Ed Sheeran',
    artistId: 'artist-ed-sheeran',
    album: '÷ (Divide)',
    duration: '4:23',
    durationSec: 263,
    cover: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-ed-2.m4a',
    plays: '2,920,400,000',
    lyrics: "I found a love for me\\nOh, darlin', just dive right in and follow my lead\\nWell, I found a girl, beautiful and sweet\\nOh, I never knew you were the someone waitin' for me\\n'Cause we were just kids when we fell in love\\nNot knowin' what it was\\nI will not give you up this time\\nDarling, just kiss me slow, your heart is all I own\\nAnd in your eyes, you're holding mine\\nBaby, I'm dancing in the dark with you between my arms",
    color: '#06b6d4',
  },
  {
    id: 'track-ed-3',
    title: 'Bad Habits',
    artist: 'Ed Sheeran',
    artistId: 'artist-ed-sheeran',
    album: '= (Equals)',
    duration: '3:51',
    durationSec: 231,
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-ed-3.m4a',
    plays: '1,940,800,000',
    lyrics: "My bad habits lead to wide eyes starin' at the ceilin'\\nLookin' for a way to let it go\\nMy bad habits lead to late nights, endin' alone\\nConversations with a stranger I barely know\\nSwearin' this will be the last, but it probably won't\\nI got nothin' left to lose, or use, or do\\nMy bad habits lead to you",
    color: '#f43f5e',
  },

  // --- OLIVIA RODRIGO ---
  {
    id: 'track-olivia-1',
    title: 'vampire',
    artist: 'Olivia Rodrigo',
    artistId: 'artist-olivia-rodrigo',
    album: 'GUTS',
    duration: '3:39',
    durationSec: 219,
    cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-olivia-1.m4a',
    plays: '1,420,300,000',
    lyrics: "Hate to give the satisfaction, undin' my reaction\\nDenyin' every move you made\\nI should've known it was strange\\nYou only come out at night\\nI used to think I was smart\\nBloodsucker, fame fucker\\nBleedin' me dry like a goddamn vampire!",
    color: '#8b5cf6',
  },
  {
    id: 'track-olivia-2',
    title: 'drivers license',
    artist: 'Olivia Rodrigo',
    artistId: 'artist-olivia-rodrigo',
    album: 'SOUR',
    duration: '4:02',
    durationSec: 242,
    cover: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-olivia-2.m4a',
    plays: '2,240,100,000',
    lyrics: "I got my driver's license last week\\nJust like we always talked about\\n'Cause you were so excited for me\\nTo finally drive up to your house\\nBut today I drove through the suburbs\\nCrying 'cause you weren't around\\nAnd you're probably with that blonde girl\\nWho always made me doubt\\nShe's so much older than me\\nShe's everything I'm insecure about",
    color: '#a855f7',
  },
  {
    id: 'track-olivia-3',
    title: 'good 4 u',
    artist: 'Olivia Rodrigo',
    artistId: 'artist-olivia-rodrigo',
    album: 'SOUR',
    duration: '2:58',
    durationSec: 178,
    cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-olivia-3.m4a',
    plays: '2,110,800,000',
    lyrics: "Well, good for you, I guess you moved on really easily\\nYou found a new girl and it only took a couple weeks\\nRemember when you said that you wanted to give me the world?\\nAnd good for you, I guess that you've been workin' on yourself\\nI guess that therapist I found for you, she really helped\\nNow you can be a better man for your brand new girl!\\nGood for you, you look happy and healthy, not me, if you ever cared to ask",
    color: '#10b981',
  },

  // --- TRAVIS SCOTT ---
  {
    id: 'track-travis-1',
    title: 'FE!N (feat. Playboi Carti)',
    artist: 'Travis Scott',
    artistId: 'artist-travis-scott',
    album: 'UTOPIA',
    duration: '3:11',
    durationSec: 191,
    cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-travis-1.m4a',
    plays: '1,540,200,000',
    lyrics: "Just come outside, for the night (yeah)\\nTake your time, get your light (yeah)\\nJohnny Dang, yeah, yeah\\nFE!N, FE!N, FE!N, FE!N, FE!N (yeah)\\nFE!N, FE!N, FE!N, FE!N, FE!N (yeah)\\nThe career's more at stake when you in your prime\\nFuck that shit, FE!N!",
    color: '#f59e0b',
  },
  {
    id: 'track-travis-2',
    title: 'SICKO MODE',
    artist: 'Travis Scott',
    artistId: 'artist-travis-scott',
    album: 'ASTROWORLD',
    duration: '5:12',
    durationSec: 312,
    cover: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-travis-2.m4a',
    plays: '2,420,119,000',
    lyrics: "Astro, yeah\\nSun is down, freezin' cold\\nThat's how we already know winter's here\\nMy dawg would probably do it for a Louis belt\\nThat's just all he know, he don't know nothin' else\\nI tried to show 'em, yeah\\nI tried to show 'em, yeah, yeah\\nYeah, yeah, yeah\\nGone on you with the pick and roll\\nYoung La Flame, he in sicko mode",
    color: '#dc2626',
  },
  {
    id: 'track-travis-3',
    title: 'goosebumps',
    artist: 'Travis Scott',
    artistId: 'artist-travis-scott',
    album: 'Birds in the Trap Sing McKnight',
    duration: '4:03',
    durationSec: 243,
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-travis-3.m4a',
    plays: '2,620,400,000',
    lyrics: "I get those goosebumps every time, yeah, you come around, yeah\\nYou ease my mind, you make everything feel fine\\nWorried 'bout those comments, that's way off\\nI get those goosebumps every time, yeah",
    color: '#ef4444',
  },

  // --- COLDPLAY ---
  {
    id: 'track-coldplay-1',
    title: 'Yellow',
    artist: 'Coldplay',
    artistId: 'artist-coldplay',
    album: 'Parachutes',
    duration: '4:29',
    durationSec: 269,
    cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-coldplay-1.m4a',
    plays: '2,890,400,000',
    lyrics: "Look at the stars\\nLook how they shine for you\\nAnd everything you do\\nYeah, they were all yellow\\nI came along\\nI wrote a song for you\\nAnd all the things you do\\nAnd it was called 'Yellow'\\nSo then I took my turn\\nOh, what a thing to have done\\nAnd it was all yellow",
    color: '#eab308',
  },
  {
    id: 'track-coldplay-2',
    title: 'Viva La Vida',
    artist: 'Coldplay',
    artistId: 'artist-coldplay',
    album: 'Viva la Vida or Death and All His Friends',
    duration: '4:02',
    durationSec: 242,
    cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-coldplay-2.m4a',
    plays: '2,310,200,000',
    lyrics: "I used to rule the world\\nSeas would rise when I gave the word\\nNow in the morning I sleep alone\\nSweep the streets I used to own\\nI used to roll the dice\\nFeel the fear in my enemy's eyes\\nListen as the crowd would sing\\n'Now the old king is dead, long live the king!'\\nOne minute I held the key\\nNext the walls were closed on me\\nAnd I discovered that my castles stand\\nUpon pillars of salt and pillars of sand",
    color: '#d97706',
  },
  {
    id: 'track-coldplay-3',
    title: 'My Universe (feat. BTS)',
    artist: 'Coldplay & BTS',
    artistId: 'artist-coldplay',
    album: 'Music of the Spheres',
    duration: '3:48',
    durationSec: 228,
    cover: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-coldplay-3.m4a',
    plays: '1,490,500,000',
    lyrics: "You, you are my universe and\\nI just want to put you first\\nAnd you, you are my universe, and\\nYou make my world light up inside\\n매일 밤 네게 날아가\\n꿈이란 것도 잊은 채\\n나 웃으며 너를 만나\\nNever-ending forever, baby",
    color: '#8b5cf6',
  },

  // --- SZA ---
  {
    id: 'track-sza-1',
    title: 'Kill Bill',
    artist: 'SZA',
    artistId: 'artist-sza',
    album: 'SOS',
    duration: '2:33',
    durationSec: 153,
    cover: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-sza-1.m4a',
    plays: '2,100,400,000',
    lyrics: "I'm still a fan even though I was salty\\nHate to see you with some other broad, know you happy\\nHate to see you happy if I'm not the one driving\\nI'm so mature, I'm so mature\\nI'm so mature, I got me a therapist to tell me there's other men\\nI don't want none, I just want you\\nIf I can't have you, no one should\\nI might kill my ex, not the best idea\\nHis new girlfriend's next, how'd I get here?\\nI might kill my ex, I still love him though\\nRather be in hell than alone",
    color: '#dc2626',
  },
  {
    id: 'track-sza-2',
    title: 'Snooze',
    artist: 'SZA',
    artistId: 'artist-sza',
    album: 'SOS',
    duration: '3:21',
    durationSec: 201,
    cover: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-sza-2.m4a',
    plays: '1,780,200,000',
    lyrics: "I'll touch that fire for you\\nI do that three, four times again, I testify for you\\nTold myself that I would do that for you\\nI can't lose when I'm with you\\nHow can I snooze and miss the moment?\\nYou just too important\\nNobody do body like you do",
    color: '#f97316',
  },

  // --- ARIJIT SINGH ---
  {
    id: 'track-arijit-1',
    title: 'Kesariya',
    artist: 'Pritam & Arijit Singh',
    artistId: 'artist-arijit-singh',
    album: 'Brahmastra',
    duration: '4:28',
    durationSec: 268,
    cover: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-arijit-1.m4a',
    plays: '1,450,800,000',
    lyrics: "Mujhko itna bataye koi\\nKaise tujhse dil na lagaye koi\\nRabba ne tujhko banane mein\\nKardi hai husn ki khaali tijoriyan\\nKajal ki siyahi se likhi\\nHai tune jaane kitno ki love storiyan\\nKesariya tera ishq hai piya\\nRang jaaun jo main haath lagaun\\nDin beete saara teri fikr mein\\nRain saari teri khair manaun",
    color: '#f59e0b',
  },
  {
    id: 'track-arijit-2',
    title: 'Tum Hi Ho',
    artist: 'Arijit Singh',
    artistId: 'artist-arijit-singh',
    album: 'Aashiqui 2',
    duration: '4:22',
    durationSec: 262,
    cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-arijit-2.m4a',
    plays: '1,120,400,000',
    lyrics: "Hum tere bin ab reh nahi sakte\\nTere bina kya wajood mera\\nTujhse juda agar ho jayenge\\nToh khud se hi ho jayenge juda\\nKyunki tum hi ho\\nAb tum hi ho\\nZindagi ab tum hi ho\\nChain bhi, mera dard bhi\\nMeri aashiqui ab tum hi ho",
    color: '#0284c7',
  },
  {
    id: 'track-arijit-3',
    title: 'Chaleya',
    artist: 'Arijit Singh & Shilpa Rao',
    artistId: 'artist-arijit-singh',
    album: 'Jawan',
    duration: '3:20',
    durationSec: 200,
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-arijit-3.m4a',
    plays: '980,100,000',
    lyrics: "Ishq mein dil bana hai\\nIshq mein dil fana hai\\nHo mita de ya bana de\\nMaine tujhko chuna hai\\nTere siva main sochu kisko\\nTu hi bata de mujhko\\nChaleya teri ore chaleya",
    color: '#ec4899',
  },

  // --- TAME IMPALA ---
  {
    id: 'track-3',
    title: 'The Less I Know The Better',
    artist: 'Tame Impala',
    artistId: 'artist-tame-impala',
    album: 'Currents',
    duration: '3:36',
    durationSec: 216,
    cover: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-3.m4a',
    plays: '1,920,302,112',
    lyrics: "Someone said they left together\\nI ran out the door to get her\\nShe was holding hands with Trevor\\nNot the greatest feeling ever\\nSaid 'Pull yourself together, boy, you've got to count your stars'\\nDon't make me wait, don't make me wait",
    color: '#ec4899',
  },
  {
    id: 'track-12',
    title: 'Borderline',
    artist: 'Tame Impala',
    artistId: 'artist-tame-impala',
    album: 'The Slow Rush',
    duration: '3:57',
    durationSec: 237,
    cover: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-12.m4a',
    plays: '920,410,230',
    lyrics: "Gone a little far, gone a little far this time for something\\nHow was I to know? How was I to know this dark will come, and\\nStarting to believe, starting to believe we're all or nothing\\nWe're on the borderline\\nCaught between the tides of pain and rapture",
    color: '#14b8a6',
  },
  {
    id: 'track-16',
    title: 'Lost in Yesterday',
    artist: 'Tame Impala',
    artistId: 'artist-tame-impala',
    album: 'The Slow Rush',
    duration: '4:09',
    durationSec: 249,
    cover: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-16.m4a',
    plays: '580,890,100',
    lyrics: "When we were living in squalor, wasn't it true poetry?\\nBack when we used to get on it, four-day benders were free\\nIt's only memories, only memories now\\nIf it calls you, embrace it\\nIf it haunts you, face it\\nLet it go, let it lead you into yesterday",
    color: '#a855f7',
  },

  // --- DAFT PUNK ---
  {
    id: 'track-7',
    title: 'Get Lucky',
    artist: 'Daft Punk',
    artistId: 'artist-daft-punk',
    album: 'Random Access Memories',
    duration: '4:08',
    durationSec: 248,
    cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-7.m4a',
    plays: '1,510,890,123',
    lyrics: "Like the legend of the phoenix\\nAll ends with beginnings\\nWhat keeps the planet spinning, uh\\nThe force from the beginning\\nWe've come too far to give up who we are\\nSo let's raise the bar and our cups to the stars\\nShe's up all night 'til the sun\\nI'm up all night to get some\\nShe's up all night for good fun\\nI'm up all night to get lucky",
    color: '#f59e0b',
  },
  {
    id: 'track-13',
    title: 'Instant Crush',
    artist: 'Daft Punk',
    artistId: 'artist-daft-punk',
    album: 'Random Access Memories',
    duration: '5:37',
    durationSec: 337,
    cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-13.m4a',
    plays: '710,120,400',
    lyrics: "I didn't want to be the one to forget\\nI thought of everything I'd never regret\\nA little time with you is all that I get\\nThat's all we need because it's all we can take\\nOne ladder to another, we're climbing\\nAnd if it's true, I will understand",
    color: '#f97316',
  },

  // --- CLASSIC INDIE & R&B HITS ---
  {
    id: 'track-6',
    title: 'Midnight City',
    artist: 'M83',
    artistId: 'artist-m83',
    album: "Hurry Up, We're Dreaming",
    duration: '4:03',
    durationSec: 243,
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-6.m4a',
    plays: '1,010,520,311',
    lyrics: "Waiting in a car\\nWaiting for a ride in the dark\\nThe night city grows\\nLook and see her eyes, they glow\\nWaiting in a car\\nWaiting for a ride in the dark\\nThe city is my church\\nIt wraps me in the blinding twilight",
    color: '#8b5cf6',
  },
  {
    id: 'track-9',
    title: 'Pink + White',
    artist: 'Frank Ocean',
    artistId: 'artist-frank-ocean',
    album: 'Blonde',
    duration: '3:04',
    durationSec: 184,
    cover: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=600&auto=format&fit=crop&q=85',
    audioSrc: '/audio/track-9.m4a',
    plays: '1,380,401,980',
    lyrics: "Yeah, yeah, yeah, yeah\\nThat's the way everyday goes\\nEvery time we have no control\\nIf the sky is pink and white\\nIf the ground is black and yellow\\nIt's the same way you showed me\\nNod my head, don't close my eyes\\nHalfway in, halfway out",
    color: '#db2777',
  }
];

export const artists = [
  {
    id: 'artist-the-weeknd',
    name: 'The Weeknd',
    verified: true,
    monthlyListeners: '108,420,195',
    worldRank: '#1 in the world',
    banner: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=85',
    genre: 'R&B / Pop / Synthwave',
    bio: 'Abel Makkonen Tesfaye, known professionally as The Weeknd, is a Canadian singer, songwriter, and record producer known for his sonic versatility and dark lyricism. His music explores escapism, romance, and melancholia, and is often inspired by personal experiences.',
    popularTrackIds: ['track-1', 'track-5', 'track-11'],
    albums: [
      { id: 'after-hours', title: 'After Hours', year: '2020', type: 'Album', cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&auto=format&fit=crop&q=85' },
      { id: 'starboy', title: 'Starboy', year: '2016', type: 'Album', cover: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'dancing-in-the-flames', title: 'Dancing In The Flames', year: '2024', type: 'Single', cover: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-taylor-swift',
    name: 'Taylor Swift',
    verified: true,
    monthlyListeners: '105,210,900',
    worldRank: '#2 in the world',
    banner: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=85',
    genre: 'Pop / Country / Indie Folk',
    bio: 'Taylor Alison Swift is an American singer-songwriter. A cultural figurehead of the 21st century, she is recognized for her songwriting, musical versatility, artistic reinventions, and global influence on the music industry. She is the highest-grossing live tour artist in history.',
    popularTrackIds: ['track-taylor-1', 'track-taylor-2'],
    albums: [
      { id: 'lover', title: 'Lover', year: '2019', type: 'Album', cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&auto=format&fit=crop&q=85' },
      { id: 'midnights', title: 'Midnights', year: '2022', type: 'Album', cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'cruel-summer-single', title: 'Cruel Summer', year: '2023', type: 'Single', cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-bruno-mars',
    name: 'Bruno Mars',
    verified: true,
    monthlyListeners: '118,240,300',
    worldRank: '#3 in the world',
    banner: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=85',
    genre: 'Pop / R&B / Funk',
    bio: 'Peter Gene Hernandez, known professionally as Bruno Mars, is an American singer-songwriter and record producer. Renowned for his stage performances, retro showmanship, and performing in a wide range of musical styles including pop, R&B, funk, and reggae.',
    popularTrackIds: ['track-bruno-1', 'track-bruno-2', 'track-bruno-3'],
    albums: [
      { id: '24k-magic', title: '24K Magic', year: '2016', type: 'Album', cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=85' },
      { id: 'unorthodox-jukebox', title: 'Unorthodox Jukebox', year: '2012', type: 'Album', cover: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'die-with-a-smile', title: 'Die With A Smile', year: '2024', type: 'Single', cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-billie-eilish',
    name: 'Billie Eilish',
    verified: true,
    monthlyListeners: '98,302,800',
    worldRank: '#4 in the world',
    banner: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=85',
    genre: 'Alternative Pop / Electropop',
    bio: 'Billie Eilish Pirate Baird O\\'Connell is an American singer-songwriter. She first gained public attention in 2015 with her debut single "Ocean Eyes". Across her career she has won multiple Grammy Awards and two Academy Awards.',
    popularTrackIds: ['track-billie-2', 'track-4', 'track-15'],
    albums: [
      { id: 'hit-me-hard-and-soft', title: 'HIT ME HARD AND SOFT', year: '2024', type: 'Album', cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=85' },
      { id: 'when-we-all-fall-asleep', title: 'WHEN WE ALL FALL ASLEEP', year: '2019', type: 'Album', cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'what-was-i-made-for', title: 'What Was I Made For?', year: '2023', type: 'Single', cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-sabrina-carpenter',
    name: 'Sabrina Carpenter',
    verified: true,
    monthlyListeners: '91,410,200',
    worldRank: '#5 in the world',
    banner: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=600&auto=format&fit=crop&q=85',
    genre: 'Pop / Dance-Pop',
    bio: 'Sabrina Annlynn Carpenter is an American singer and actress. With breakout mega-hits "Espresso" and "Please Please Please", she achieved historic consecutive multi-week #1 positions across global Billboard charts and broke Spotify streaming records.',
    popularTrackIds: ['track-sabrina-1', 'track-sabrina-2'],
    albums: [
      { id: 'short-n-sweet', title: 'Short n\\' Sweet', year: '2024', type: 'Album', cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'espresso-single', title: 'Espresso', year: '2024', type: 'Single', cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-drake',
    name: 'Drake',
    verified: true,
    monthlyListeners: '86,390,200',
    worldRank: '#6 in the world',
    banner: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=85',
    genre: 'Hip-Hop / Rap / Trap',
    bio: 'Aubrey Drake Graham is a Canadian rapper, singer, and songwriter. An influential figure in contemporary popular music, he has been credited for popularizing R&B sensibilities in hip hop and holds the record for most charted songs on the Billboard Hot 100.',
    popularTrackIds: ['track-drake-1', 'track-drake-2', 'track-drake-3'],
    albums: [
      { id: 'scorpion', title: 'Scorpion', year: '2018', type: 'Album', cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&auto=format&fit=crop&q=85' },
      { id: 'views', title: 'Views', year: '2016', type: 'Album', cover: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'gods-plan', title: "God's Plan", year: '2018', type: 'Single', cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-post-malone',
    name: 'Post Malone',
    verified: true,
    monthlyListeners: '82,750,400',
    worldRank: '#7 in the world',
    banner: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=85',
    genre: 'Pop / Hip-Hop / Rock',
    bio: 'Austin Richard Post, known professionally as Post Malone, is an American rapper, singer, songwriter, and record producer known for blending genres and his introspective songwriting.',
    popularTrackIds: ['track-post-1', 'track-post-2', 'track-post-3'],
    albums: [
      { id: 'hollywoods-bleeding', title: "Hollywood's Bleeding", year: '2019', type: 'Album', cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=85' },
      { id: 'beerbongs-bentleys', title: 'beerbongs & bentleys', year: '2018', type: 'Album', cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'sunflower-single', title: 'Sunflower', year: '2018', type: 'Single', cover: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-ariana-grande',
    name: 'Ariana Grande',
    verified: true,
    monthlyListeners: '85,410,200',
    worldRank: '#8 in the world',
    banner: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=85',
    genre: 'Pop / R&B',
    bio: 'Ariana Grande-Butera is an American singer, songwriter, and actress known for her four-octave vocal range and signature whistle register. One of the best-selling music artists of all time with multiple Grammy Awards.',
    popularTrackIds: ['track-ariana-1', 'track-ariana-2', 'track-ariana-3'],
    albums: [
      { id: 'eternal-sunshine', title: 'eternal sunshine', year: '2024', type: 'Album', cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&auto=format&fit=crop&q=85' },
      { id: 'thank-u-next', title: 'thank u, next', year: '2019', type: 'Album', cover: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: '7-rings-single', title: '7 rings', year: '2019', type: 'Single', cover: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-ed-sheeran',
    name: 'Ed Sheeran',
    verified: true,
    monthlyListeners: '76,210,000',
    worldRank: '#9 in the world',
    banner: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=85',
    genre: 'Pop / Folk-Pop / Acoustic',
    bio: 'Edward Christopher Sheeran MBE is an English singer-songwriter. With hits like "Shape of You" and "Perfect", he is one of the world\\'s best-selling music artists and holds the UK record for most weeks at #1.',
    popularTrackIds: ['track-ed-1', 'track-ed-2', 'track-ed-3'],
    albums: [
      { id: 'divide', title: '÷ (Divide)', year: '2017', type: 'Album', cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&auto=format&fit=crop&q=85' },
      { id: 'equals', title: '= (Equals)', year: '2021', type: 'Album', cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'shape-of-you-single', title: 'Shape of You', year: '2017', type: 'Single', cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-dua-lipa',
    name: 'Dua Lipa',
    verified: true,
    monthlyListeners: '79,915,204',
    worldRank: '#10 in the world',
    banner: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&auto=format&fit=crop&q=85',
    genre: 'Dance-Pop / Disco',
    bio: 'Dua Lipa is an English and Albanian singer and songwriter. Known for her signature mezzo-soprano vocal range and disco-influenced pop sound, she has won three Grammy Awards and seven Brit Awards.',
    popularTrackIds: ['track-2', 'track-10'],
    albums: [
      { id: 'future-nostalgia', title: 'Future Nostalgia', year: '2020', type: 'Album', cover: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'houdini', title: 'Houdini', year: '2023', type: 'Single', cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-kendrick-lamar',
    name: 'Kendrick Lamar',
    verified: true,
    monthlyListeners: '72,820,105',
    worldRank: '#11 in the world',
    banner: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=85',
    genre: 'Hip-Hop / Conscious Rap',
    bio: 'Kendrick Lamar Duckworth is an American rapper and songwriter. Regarded as one of the most influential hip-hop artists of his generation, he was awarded the Pulitzer Prize for Music in 2018.',
    popularTrackIds: ['track-8', 'track-kendrick-2', 'track-14'],
    albums: [
      { id: 'damn', title: 'DAMN.', year: '2017', type: 'Album', cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'not-like-us', title: 'Not Like Us', year: '2024', type: 'Single', cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-travis-scott',
    name: 'Travis Scott',
    verified: true,
    monthlyListeners: '71,450,900',
    worldRank: '#12 in the world',
    banner: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=85',
    genre: 'Hip-Hop / Trap / Psychedelic Rap',
    bio: 'Jacques Bermon Webster II, known professionally as Travis Scott, is an American rapper, singer, songwriter, and record producer known for his heavy autotuned ambient trap style and high-energy stadium tours.',
    popularTrackIds: ['track-travis-1', 'track-travis-2', 'track-travis-3'],
    albums: [
      { id: 'utopia', title: 'UTOPIA', year: '2023', type: 'Album', cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&auto=format&fit=crop&q=85' },
      { id: 'astroworld', title: 'ASTROWORLD', year: '2018', type: 'Album', cover: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'fein-single', title: 'FE!N', year: '2023', type: 'Single', cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-olivia-rodrigo',
    name: 'Olivia Rodrigo',
    verified: true,
    monthlyListeners: '64,120,400',
    worldRank: '#14 in the world',
    banner: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=85',
    genre: 'Pop Rock / Alt Pop',
    bio: 'Olivia Isabel Rodrigo is an American singer-songwriter and actress. She gained fame with her record-breaking debut single "drivers license" and albums "SOUR" and "GUTS", earning three Grammy Awards.',
    popularTrackIds: ['track-olivia-1', 'track-olivia-2', 'track-olivia-3'],
    albums: [
      { id: 'guts', title: 'GUTS', year: '2023', type: 'Album', cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=85' },
      { id: 'sour', title: 'SOUR', year: '2021', type: 'Album', cover: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'vampire-single', title: 'vampire', year: '2023', type: 'Single', cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-coldplay',
    name: 'Coldplay',
    verified: true,
    monthlyListeners: '88,940,300',
    worldRank: '#15 in the world',
    banner: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=85',
    genre: 'Alternative Rock / Stadium Pop',
    bio: 'Coldplay are a British rock band formed in London in 1997. Consisting of vocalists and pianist Chris Martin, guitarist Jonny Buckland, bassist Guy Berryman, and drummer Will Champion. They have sold over 100 million records worldwide.',
    popularTrackIds: ['track-coldplay-1', 'track-coldplay-2', 'track-coldplay-3'],
    albums: [
      { id: 'parachutes', title: 'Parachutes', year: '2000', type: 'Album', cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=85' },
      { id: 'viva-la-vida-album', title: 'Viva la Vida', year: '2008', type: 'Album', cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'my-universe', title: 'My Universe', year: '2021', type: 'Single', cover: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-sza',
    name: 'SZA',
    verified: true,
    monthlyListeners: '67,110,800',
    worldRank: '#16 in the world',
    banner: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=600&auto=format&fit=crop&q=85',
    genre: 'R&B / Neo-Soul',
    bio: 'Solána Imani Rowe, known professionally as SZA, is an American singer and songwriter. Her critically acclaimed albums "Ctrl" and "SOS" earned her international superstardom and multiple Grammy Awards.',
    popularTrackIds: ['track-sza-1', 'track-sza-2'],
    albums: [
      { id: 'sos', title: 'SOS', year: '2022', type: 'Album', cover: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'kill-bill-single', title: 'Kill Bill', year: '2023', type: 'Single', cover: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-bts',
    name: 'BTS',
    verified: true,
    monthlyListeners: '46,892,100',
    worldRank: '#20 in the world',
    banner: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=85',
    genre: 'K-Pop / Pop / Hip-Hop',
    bio: 'BTS (Bangtan Sonyeondan), also known as the Bangtan Boys, is a 21st-century pop icons band from South Korea. The septet consists of RM, Jin, SUGA, j-hope, Jimin, V, and Jung Kook. Gaining global recognition for their authentic, self-produced music, top-notch performances, and the way they interact with their fans, BTS has established themselves as global superstars, breaking countless world records and topping the Billboard charts.',
    popularTrackIds: ['track-bts-1', 'track-bts-2', 'track-bts-3', 'track-bts-4', 'track-bts-5', 'track-bts-6', 'track-bts-7', 'track-bts-8', 'track-bts-9', 'track-bts-10'],
    albums: [
      { id: 'be', title: 'BE', year: '2020', type: 'Album', cover: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&auto=format&fit=crop&q=85' },
      { id: 'map-of-the-soul-7', title: 'Map of the Soul: 7', year: '2020', type: 'Album', cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=85' },
      { id: 'butter-single', title: 'Butter', year: '2021', type: 'Single', cover: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'dynamite-single', title: 'Dynamite', year: '2020', type: 'Single', cover: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-arijit-singh',
    name: 'Arijit Singh',
    verified: true,
    monthlyListeners: '96,400,200',
    worldRank: '#1 in India',
    banner: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=85',
    genre: 'Bollywood / Soul / Romantic',
    bio: 'Arijit Singh is an Indian playback singer and music composer. The undisputed voice of Indian romance and melody, he is the most streamed Indian artist in Spotify history and holds massive global recognition.',
    popularTrackIds: ['track-arijit-1', 'track-arijit-2', 'track-arijit-3'],
    albums: [
      { id: 'brahmastra', title: 'Brahmastra', year: '2022', type: 'Album', cover: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&auto=format&fit=crop&q=85' },
      { id: 'aashiqui-2', title: 'Aashiqui 2', year: '2013', type: 'Album', cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'kesariya-single', title: 'Kesariya', year: '2022', type: 'Single', cover: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-daft-punk',
    name: 'Daft Punk',
    verified: true,
    monthlyListeners: '29,614,200',
    worldRank: '#88 in the world',
    banner: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=85',
    genre: 'Electronic / French Touch / Synth-Pop',
    bio: 'Daft Punk was a French electronic music duo formed in 1993 in Paris by Thomas Bangalter and Guy-Manuel de Homem-Christo. Widely considered one of the most influential acts in dance music history.',
    popularTrackIds: ['track-7', 'track-13'],
    albums: [
      { id: 'random-access-memories', title: 'Random Access Memories', year: '2013', type: 'Album', cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'get-lucky-single', title: 'Get Lucky', year: '2013', type: 'Single', cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&auto=format&fit=crop&q=85' },
    ]
  },
  {
    id: 'artist-tame-impala',
    name: 'Tame Impala',
    verified: true,
    monthlyListeners: '33,108,442',
    worldRank: '#72 in the world',
    banner: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=1600&auto=format&fit=crop&q=90',
    avatar: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=600&auto=format&fit=crop&q=85',
    genre: 'Psychedelic Rock / Synth-Pop',
    bio: 'Tame Impala is the psychedelic music project of Australian multi-instrumentalist Kevin Parker. In the recording studio, Parker writes, records, performs, and produces all of the project\\'s music.',
    popularTrackIds: ['track-3', 'track-12', 'track-16'],
    albums: [
      { id: 'currents', title: 'Currents', year: '2015', type: 'Album', cover: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=400&auto=format&fit=crop&q=85' },
    ],
    singles: [
      { id: 'borderline-single', title: 'Borderline', year: '2019', type: 'Single', cover: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=400&auto=format&fit=crop&q=85' },
    ]
  }
];

export const playlists = [
  {
    id: 'todays-top-hits',
    title: "Today's Top Hits",
    description: "The hottest tracks across the globe right now: Bruno Mars, Sabrina Carpenter, Billie Eilish & more.",
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=85',
    saves: '35,812,490',
    owner: 'Spotify',
    gradient: 'from-emerald-900 via-zinc-900 to-black',
    accentColor: '#10b981',
    trackIds: ['track-1', 'track-bruno-1', 'track-sabrina-1', 'track-billie-2', 'track-taylor-1', 'track-post-1', 'track-drake-1'],
  },
  {
    id: 'this-is-bts',
    title: 'This Is BTS',
    description: 'The essential tracks from the global icons: Dynamite, Butter, Boy With Luv, and more.',
    cover: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=85',
    saves: '9,420,400',
    owner: 'Spotify',
    gradient: 'from-purple-950 via-zinc-950 to-black',
    accentColor: '#a855f7',
    trackIds: ['track-bts-1', 'track-bts-2', 'track-bts-3', 'track-bts-4', 'track-bts-5', 'track-bts-6', 'track-bts-7', 'track-bts-8', 'track-bts-9', 'track-bts-10'],
  },
  {
    id: 'hip-hop-central',
    title: 'Hip-Hop Central',
    description: 'The titans of rap: Kendrick Lamar, Drake, Travis Scott, and Post Malone.',
    cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=85',
    saves: '22,390,440',
    owner: 'Spotify',
    gradient: 'from-amber-950 via-zinc-900 to-black',
    accentColor: '#f59e0b',
    trackIds: ['track-8', 'track-kendrick-2', 'track-drake-1', 'track-travis-1', 'track-travis-2', 'track-post-3', 'track-14'],
  },
  {
    id: 'chill-vibes',
    title: 'Chill Vibes & Lofi',
    description: 'Kick back with warm beats, smooth mellow synths, and calming rhythms.',
    cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=85',
    saves: '13,240,230',
    owner: 'Spotify',
    gradient: 'from-indigo-950 via-zinc-900 to-black',
    accentColor: '#6366f1',
    trackIds: ['track-3', 'track-6', 'track-9', 'track-12', 'track-15', 'track-16', 'track-ed-2'],
  },
  {
    id: 'pop-superstars',
    title: 'Pop Superstars',
    description: 'Chart-toppers by Ariana Grande, Taylor Swift, Ed Sheeran, Olivia Rodrigo & Sabrina Carpenter.',
    cover: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=600&auto=format&fit=crop&q=85',
    saves: '18,410,000',
    owner: 'Spotify',
    gradient: 'from-rose-950 via-zinc-900 to-black',
    accentColor: '#f43f5e',
    trackIds: ['track-taylor-1', 'track-sabrina-1', 'track-ariana-1', 'track-ed-1', 'track-olivia-1', 'track-2'],
  },
  {
    id: 'desi-hits',
    title: 'Desi Soul & Romance',
    description: 'Soulful Bollywood hits featuring Arijit Singh, Pritam, and chart-topping romantic ballads.',
    cover: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=85',
    saves: '11,105,400',
    owner: 'Spotify',
    gradient: 'from-orange-950 via-zinc-900 to-black',
    accentColor: '#f97316',
    trackIds: ['track-arijit-1', 'track-arijit-2', 'track-arijit-3'],
  },
  {
    id: 'deep-focus',
    title: 'Deep Focus & Study',
    description: 'Keep calm and focus with ambient electronic soundscapes and subtle rhythmic pulses.',
    cover: 'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=600&auto=format&fit=crop&q=85',
    saves: '8,415,900',
    owner: 'Spotify',
    gradient: 'from-teal-950 via-zinc-900 to-black',
    accentColor: '#14b8a6',
    trackIds: ['track-6', 'track-7', 'track-12', 'track-13', 'track-coldplay-1'],
  },
  {
    id: 'workout-fuel',
    title: 'Workout Fuel',
    description: 'High-energy bangers to smash your PR and push past the limits.',
    cover: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=85',
    saves: '10,210,400',
    owner: 'Spotify',
    gradient: 'from-lime-950 via-zinc-900 to-black',
    accentColor: '#84cc16',
    trackIds: ['track-travis-1', 'track-8', 'track-post-3', 'track-bts-9', 'track-2'],
  },
  {
    id: 'liked-songs',
    title: 'Liked Songs',
    description: 'Your personal collection of saved favorite tracks.',
    cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=85',
    saves: 'By You',
    owner: 'Alex Rivera',
    gradient: 'from-violet-900 via-indigo-950 to-black',
    accentColor: '#8b5cf6',
    trackIds: ['track-1', 'track-bts-1', 'track-sabrina-1', 'track-taylor-1', 'track-bruno-1', 'track-billie-2', 'track-drake-1'],
  },
];

export const podcasts = [
  {
    id: 'podcast-huberman',
    title: 'Huberman Lab',
    publisher: 'Scicomm Media',
    description: 'Dr. Andrew Huberman discusses neuroscience: how our brain and its connections with the organs of our body control our perceptions, our behaviors, and our health.',
    cover: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=500&auto=format&fit=crop&q=85',
    episodesCount: 184,
    latestEpisode: 'Master Your Sleep & Reset Your Circadian Clock',
    duration: '2 hr 14 min',
  },
  {
    id: 'podcast-song-exploder',
    title: 'Song Exploder',
    publisher: 'Hrishikesh Hirway',
    description: 'Musicians take apart their songs, and piece by piece, tell the story of how they were made.',
    cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=85',
    episodesCount: 260,
    latestEpisode: 'Dua Lipa – Levitating Breakdown',
    duration: '22 min',
  },
  {
    id: 'podcast-darknet',
    title: 'Darknet Diaries',
    publisher: 'Jack Rhysider',
    description: 'True stories from the dark side of the Internet with hackers, cybercrime, and shadowy operatives.',
    cover: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=500&auto=format&fit=crop&q=85',
    episodesCount: 142,
    latestEpisode: 'EP 142: Operation Triangulation',
    duration: '58 min',
  },
  {
    id: 'podcast-deep-dive',
    title: 'Deep Dive with Ali Abdaal',
    publisher: 'Ali Abdaal',
    description: 'Inspiring conversations with authors, entrepreneurs, and creators about finding fulfillment and building great lives.',
    cover: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=500&auto=format&fit=crop&q=85',
    episodesCount: 96,
    latestEpisode: 'How To Build Sustainable Creative Habits',
    duration: '1 hr 18 min',
  }
];

export const userProfile = {
  name: 'Alex Rivera',
  handle: '@alexrivera',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  plan: 'Premium Individual',
  playlistsCount: 14,
  followingCount: 38,
  followersCount: 52
};

export const albums = [
  {
    id: 'album-after-hours',
    title: 'After Hours',
    artist: 'The Weeknd',
    artistId: 'artist-the-weeknd',
    year: '2020',
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=85',
    trackIds: ['track-1', 'track-11'],
    type: 'Album',
    description: 'The critically acclaimed synthwave powerhouse featuring Blinding Lights.'
  },
  {
    id: 'album-be',
    title: 'BE',
    artist: 'BTS',
    artistId: 'artist-bts',
    year: '2020',
    cover: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=85',
    trackIds: ['track-bts-1', 'track-bts-5'],
    type: 'Album',
    description: 'The monumental Billboard 200 #1 studio album featuring Dynamite and Life Goes On.'
  },
  {
    id: 'album-short-n-sweet',
    title: "Short n' Sweet",
    artist: 'Sabrina Carpenter',
    artistId: 'artist-sabrina-carpenter',
    year: '2024',
    cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=85',
    trackIds: ['track-sabrina-1', 'track-sabrina-2'],
    type: 'Album',
    description: 'Global chart-dominating pop record featuring Espresso and Please Please Please.'
  },
  {
    id: 'album-lover',
    title: 'Lover',
    artist: 'Taylor Swift',
    artistId: 'artist-taylor-swift',
    year: '2019',
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=85',
    trackIds: ['track-taylor-1'],
    type: 'Album',
    description: 'The celebrated multi-platinum pop album featuring Cruel Summer.'
  },
  {
    id: 'album-hit-me-hard',
    title: 'HIT ME HARD AND SOFT',
    artist: 'Billie Eilish',
    artistId: 'artist-billie-eilish',
    year: '2024',
    cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=85',
    trackIds: ['track-billie-2'],
    type: 'Album',
    description: 'Critically acclaimed third studio album featuring BIRDS OF A FEATHER.'
  },
  {
    id: 'album-damn',
    title: 'DAMN.',
    artist: 'Kendrick Lamar',
    artistId: 'artist-kendrick-lamar',
    year: '2017',
    cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=85',
    trackIds: ['track-8', 'track-14'],
    type: 'Album',
    description: 'Pulitzer Prize-winning hip-hop landmark featuring HUMBLE. and DNA.'
  },
  {
    id: 'album-scorpion',
    title: 'Scorpion',
    artist: 'Drake',
    artistId: 'artist-drake',
    year: '2018',
    cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=85',
    trackIds: ['track-drake-1'],
    type: 'Album',
    description: "Double album blockbuster featuring the historic smash God's Plan."
  },
  {
    id: 'album-24k-magic',
    title: '24K Magic',
    artist: 'Bruno Mars',
    artistId: 'artist-bruno-mars',
    year: '2016',
    cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=85',
    trackIds: ['track-bruno-2', 'track-bruno-3'],
    type: 'Album',
    description: 'Grammy Album of the Year winning funk and pop celebration.'
  },
  {
    id: 'album-hollywoods-bleeding',
    title: "Hollywood's Bleeding",
    artist: 'Post Malone',
    artistId: 'artist-post-malone',
    year: '2019',
    cover: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=85',
    trackIds: ['track-post-1', 'track-post-2'],
    type: 'Album',
    description: 'Chart-topping album featuring Sunflower and Circles.'
  },
  {
    id: 'album-divide',
    title: '÷ (Divide)',
    artist: 'Ed Sheeran',
    artistId: 'artist-ed-sheeran',
    year: '2017',
    cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=85',
    trackIds: ['track-ed-1', 'track-ed-2'],
    type: 'Album',
    description: 'Record-shattering multi-platinum pop album featuring Shape of You and Perfect.'
  },
  {
    id: 'album-utopia',
    title: 'UTOPIA',
    artist: 'Travis Scott',
    artistId: 'artist-travis-scott',
    year: '2023',
    cover: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=85',
    trackIds: ['track-travis-1'],
    type: 'Album',
    description: 'Visionary trap and experimental hip-hop powerhouse featuring FE!N.'
  },
  {
    id: 'album-guts',
    title: 'GUTS',
    artist: 'Olivia Rodrigo',
    artistId: 'artist-olivia-rodrigo',
    year: '2023',
    cover: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=85',
    trackIds: ['track-olivia-1'],
    type: 'Album',
    description: 'Sophomore alternative pop-rock smash featuring vampire.'
  },
  {
    id: 'album-ram',
    title: 'Random Access Memories',
    artist: 'Daft Punk',
    artistId: 'artist-daft-punk',
    year: '2013',
    cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=85',
    trackIds: ['track-7', 'track-13'],
    type: 'Album',
    description: 'Grammy Album of the Year featuring Get Lucky and Instant Crush.'
  }
];
`;

const targetPath = path.join(__dirname, '..', 'src', 'data', 'musicData.js');
fs.writeFileSync(targetPath, musicDataContent, 'utf8');
console.log('Successfully updated src/data/musicData.js with expanded data!');
